services:
  mysql:
    container_name: mysql-movie-sphere
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie_sphere
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - movie-sphere
    restart: unless-stopped

  movie-sphere:
    container_name: movie-sphere
    image: amrelsebaey/movie-sphere:1.0.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-movie-sphere:3306/movie_sphere
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - movie-sphere
    depends_on:
      - mysql
    restart: unless-stopped

  movie-sphere-ui:
    container_name: movie-sphere-ui
    image: amrelsebaey/movie-sphere-ui:1.0.0
    ports:
      - "4200:80"
    networks:
      - movie-sphere
    depends_on:
      - movie-sphere

networks:
  movie-sphere:
    driver: bridge

volumes:
  mysql:
    driver: local
