services:
  postgres:
    container_name: postgres-sql-movie-sphere
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgres/data
      POSTGRES_DB: movie_sphere
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    networks:
      - movie-sphere
    restart: unless-stopped

networks:
  movie-sphere:
    driver: bridge

volumes:
  postgres:
    driver: local