spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_sphere
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_insert: true
        order_update: true

application:
  security:
    jwt:
      secretKey: 92c9020ef7d92e560952808e67ad8527ddf131681cb04def89af23bc6c24b7ec
      expiration: 86400000
omdb:
  api:
    key: cfd7c75d

