/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { Movie } from './models/movie';
export type { PageResponseMovie } from './models/page-response-movie';
export type { Rating } from './models/rating';
export type { RegistrationRequest } from './models/registration-request';
